<?php
return [
    /*
     * |--------------------------------------------------------------------------
     * | Module Namespace
     * |--------------------------------------------------------------------------
     * |
     * | Default module namespace.
     * |
     */
    
    'namespace' => 'App\Modules',
    /*
    |--------------------------------------------------------------------------
    | Module Stubs
    |--------------------------------------------------------------------------
    |
    | Default module stubs.
    |
    */

    'stubs' => [
        'enabled' => false,
        'path' => base_path(__DIR__ . '/../src/Commands/stubs'),
        'files' => [
            'routes/web' => 'Routes/web.php',
            'routes/api' => 'Routes/api.php',
            'views/index' => 'Resources/views/index.blade.php',
            'views/master' => 'Resources/views/layouts/master.blade.php',
            'scaffold/config' => 'Config/config.php',
            'json/module' => 'module.json',
            'json/composer' => 'composer.json'
        ],
        'replacements' => [
            'routes/web' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'MODULE_NAMESPACE'
            ],
            'routes/api' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'MODULE_NAMESPACE'
            ],
            'module' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'MODULE_NAMESPACE'
            ],
            'views/index' => [
                'LOWER_NAME'
            ],
            'views/master' => [
                'STUDLY_NAME'
            ],
            'scaffold/config' => [
                'STUDLY_NAME'
            ],
            'composer' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'VENDOR',
                'AUTHOR_NAME',
                'AUTHOR_EMAIL',
                'MODULE_NAMESPACE'
            ]
        ]
    ],
    'paths' => [
        /*
         * |--------------------------------------------------------------------------
         * | Module path
         * |--------------------------------------------------------------------------
         * |
         * | This path used for save the generated module. This path also will added
         * | automatically to list of scanned folders.
         * |
         */
        
        'module' => base_path('app/Modules'),
        /*
        |--------------------------------------------------------------------------
        | Modules asset paths
        |--------------------------------------------------------------------------
        |
        | Here you may update the modules assets path.
        |
        */

        'asset' => public_path('modules'),
        /*
         |--------------------------------------------------------------------------
         | The model factory paths
         |--------------------------------------------------------------------------
         |
         | Where you run 'module:publish-factory' command, where do you publish the
         | the model factory files?
         |
         */
        
        'modelFactory' => base_path('database/factories'),
        /*
        |--------------------------------------------------------------------------
        | Generator path
        |--------------------------------------------------------------------------
        |
        | Here you may update the modules generator path.
        |
        */

        'generator' => [
            'asset' => 'Resources/assets',
            'config' => 'Config',
            'migration' => 'Database/Migrations',
            'seed' => 'Database/Seeds',
            'modelFactory' => 'Database/Factories',
            'controller' => 'Http/Controllers',
            'provider' => 'Providers',
            'lang' => 'Resources/lang',
            'view' => 'Resources/views',
            'route' => 'Routes'
        ]
    ],
    /*
    |--------------------------------------------------------------------------
    | Scan Path
    |--------------------------------------------------------------------------
    |
    | Here you define which folder will be scanned. By default will scan vendor
    | directory. This is useful if you host the package in packagist website.
    |
    */

    'scan' => [
        'enabled' => false,
        'paths' => [
            base_path('vendor/*/*')
        ]
    ],
    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    |
    */
    
    'composer' => [
        'vendor' => 'llama-laravel-modules',
        'author' => [
            'name' => 'XuaNguyen',
            'email' => 'xuan.0211@gmail.com'
        ]
    ],
    /*
    |--------------------------------------------------------------------------
    | Caching
    |--------------------------------------------------------------------------
    |
    | Here is the config for setting up caching feature.
    |
    */
    
    'cache' => [
        'enabled' => false,
        'key' => 'llama-laravel-modules',
        'lifetime' => 60
    ]
];
